version: '2'
services:
    dadbot:
        container_name: dadbot
        build:
            context: .
            dockerfile: Dockerfile
        image: dadbot:latest
        volumes:
            - .:/app
            - .:/app/node_modules
        stdin_open: true
        tty: true
        depends_on:
            - mongodb
    mongodb:
        container_name: mongodb
        image: mongo:latest
        volumes: 
            - ./data:/data/db
        expose:
            - "27017"
